opt_out_usage

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Deploy to Open Testing (Beta)"
  lane :open_test do
    upload_to_play_store(
      track: 'open',
      aab: './build/app/outputs/bundle/playRelease/app-play-release.aab',
      json_key: 'fastlane/supply.json',
      skip_upload_metadata: false,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: 'draft'
    )
  end
end
